SieuNhanGaoBlog/Areas/Admin/Controllers/BusinessRoleController.cs
using Microsoft.AspNetCore.Mvc;
using SieuNhanGao.Service.IServices;
using SieuNhanGao.Service.ViewModels;
using SieuNhanGaoBlog.Areas.Admin.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class BusinessRoleController : Controller
    {
        private IBusinessRoleService businessRoleService;
        private IRoleService roleService;

        public BusinessRoleController(IBusinessRoleService _businessRoleService
                                      , IRoleService _roleService)
        {
            businessRoleService = _businessRoleService;
            roleService = _roleService;
        }

        public IActionResult Index()
        {
            var businessRoles = businessRoleService.GetAll();
            return View(businessRoles);
        }

        // get: udpate roles to database
        public IActionResult UpdateRole()
        {
            // get controlers,action flow namespace
            IList<Type> controllers = ReflectionControler.GetControllers("SieuNhanGaoBlog.Areas.Admin.Controllers");
            // get businessRoleId in table BusinessRole
            IList<string> controlersOlds = businessRoleService.GetAll().Select(s => s.Id).ToList();
            // get Roles in table Role
            IList<string> rolesOlds = roleService.GetAll().Select(s => s.RoleName).ToList();

            // iterator listCOntroller and check it contain in role name, execute  add businessRole
            foreach (var itemController in controllers)
            {
                if (!controlersOlds.Contains(itemController.Name))
                {
                    var businessRoleVm = new BusinessRoleViewModel { Id = itemController.Name, BusinessRoleName = "chua co mo ta" };
                    businessRoleService.Add(businessRoleVm);
                }
                // get actions flow controllers
                IList<string> actions = ReflectionControler.GetActions(itemController);
                foreach (var itemRoles in actions)
                {
                    if (!rolesOlds.Contains(itemController.Name + "-" + itemRoles))
                    {
                        var rolevm = new RoleViewModel { RoleName = itemController.Name + "-" + itemRoles, BusinessRoleId = itemController.Name };
                        roleService.Add(rolevm);
                    }
                }
            }
            businessRoleService.Save();
            roleService.Save();

            return RedirectToAction(nameof(Index));
        }

        // GET: BusinessRoles/Edit/5
        public IActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return View();
            }

            var businessRoleVM = businessRoleService.FindById(id);
            if (businessRoleVM == null)
            {
                return View();
            }
            return View(businessRoleVM);
        }

        // POST: BusinessRoles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("Id,BusinessRoleName")] BusinessRoleViewModel businessRoleViewModel)
        {
            if (id != businessRoleViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                businessRoleService.Update(businessRoleViewModel);
                businessRoleService.Save();

                return RedirectToAction(nameof(Index));
            }
            return View(businessRoleViewModel);
        }

        // GET: BusinessRoles/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var businessRole = businessRoleService.FindById(id);
            if (businessRole == null)
            {
                return NotFound();
            }

            return View(businessRole);
        }

        // POST: BusinessRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            businessRoleService.Delete(id);
            businessRoleService.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using SieuNhanGao.Service.IServices;
using SieuNhanGao.Service.ViewModels;
using SieuNhanGaoBlog.Areas.Admin.Data;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class RoleController : Controller
    {
        private IRoleService roleService;

        public RoleController(IRoleService _roleService)
        {
            roleService = _roleService;
        }

        public IActionResult Index(string Id)
        {
            var roles = roleService.GetAllWithBusinessRole(Id);
            return View(roles);
        }

        // GET: Roles/Edit/5
        public IActionResult Edit(int Id)
        {
            if (Id == 0)
            {
                return View();
            }
            var role = roleService.FindById(Id);
            if (role == null)
            {
                return View();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,RoleName,Description,BusinessRoleId")] RoleViewModel roleVM)
        {
            if (id != roleVM.Id)
            {
                return View();
            }

            if (ModelState.IsValid)
            {
                roleService.Update(roleVM);
                roleService.Save();
                return RedirectToAction("Index", new { Id = roleVM.BusinessRoleId });
            }
            return View();
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Views/BusinessRole/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model SieuNhanGao.Service.ViewModels.BusinessRoleViewModel
<div class="container-fluid">
    <h1>Delete</h1>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>BusinessRole</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BusinessRoleName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BusinessRoleName)
            </dd>
        </dl>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

SieuNhanGaoBlog/Areas/Admin/Views/BusinessRole/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model SieuNhanGao.Service.ViewModels.BusinessRoleViewModel
@{
    if (Model == null)
    {
        <div class="card shadow mb-4">
            <div class="container-fluid">
                <div class="card-header py-3">
                    <div class="card-header py-3">
                        <p class="m-0 font-weight-bold text-primary">
                            <h3>Không có dữ liệu con ơi</h3>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="container-fluid">
            <h1>Edit</h1>
            <h4>BusinessRole</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="BusinessRoleName" class="control-label"></label>
                            <input asp-for="BusinessRoleName" class="form-control" />
                            <span asp-validation-for="BusinessRoleName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    }
}

SieuNhanGaoBlog/Areas/Admin/Views/BusinessRole/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<SieuNhanGao.Service.ViewModels.BusinessRoleViewModel>
@{
    <div class="card shadow mb-4">
        <div class="container-fluid">
            <div class="card-header py-3">
                <p class="m-0 font-weight-bold text-primary">
                    <a asp-area="Admin" asp-controller="BusinessRole" asp-action="UpdateRole">Update Business Role</a>
                </p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.BusinessRoleName)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BusinessRoleName)
                                    </td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="BusinessRole" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                        <a asp-area="Admin" asp-controller="Role" asp-action="Index" asp-route-id="@item.Id">Detail</a> |
                                        <a asp-area="Admin" asp-controller="BusinessRole" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            @* add phan trang *@
        </div>
    </div>
}