SieuNhanGaoBlog/Areas/Admin/Controllers/BusinessRoleController.cs
using Microsoft.AspNetCore.Mvc;
using SieuNhanGao.Service.IServices;
using SieuNhanGao.Service.ViewModels;
using SieuNhanGaoBlog.Areas.Admin.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class BusinessRoleController : Controller
    {
        private IBusinessRoleService businessRoleService;
        private IRoleService roleService;

        public BusinessRoleController(IBusinessRoleService _businessRoleService
                                      , IRoleService _roleService)
        {
            businessRoleService = _businessRoleService;
            roleService = _roleService;
        }

        public IActionResult Index()
        {
            var businessRoles = businessRoleService.GetAll();
            return View(businessRoles);
        }

        // get: udpate roles to database
        public IActionResult UpdateRole()
        {
            // get controlers,action flow namespace
            IList<Type> controllers = ReflectionControler.GetControllers("SieuNhanGaoBlog.Areas.Admin.Controllers");
            // get businessRoleId in table BusinessRole
            IList<string> controlersOlds = businessRoleService.GetAll().Select(s => s.Id).ToList();
            // get Roles in table Role
            IList<string> rolesOlds = roleService.GetAll().Select(s => s.RoleName).ToList();

            // iterator listCOntroller and check it contain in role name, execute  add businessRole
            foreach (var itemController in controllers)
            {
                if (!controlersOlds.Contains(itemController.Name))
                {
                    var businessRoleVm = new BusinessRoleViewModel { Id = itemController.Name, BusinessRoleName = "chua co mo ta" };
                    businessRoleService.Add(businessRoleVm);
                }
                // get actions flow controllers
                IList<string> actions = ReflectionControler.GetActions(itemController);
                foreach (var itemRoles in actions)
                {
                    if (!rolesOlds.Contains(itemController.Name + "-" + itemRoles))
                    {
                        var rolevm = new RoleViewModel { RoleName = itemController.Name + "-" + itemRoles, BusinessRoleId = itemController.Name };
                        roleService.Add(rolevm);
                    }
                }
            }
            businessRoleService.Save();
            roleService.Save();

            return RedirectToAction(nameof(Index));
        }

        // GET: BusinessRoles/Edit/5
        public IActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return View();
            }

            var businessRoleVM = businessRoleService.FindById(id);
            if (businessRoleVM == null)
            {
                return View();
            }
            return View(businessRoleVM);
        }

        // POST: BusinessRoles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("Id,BusinessRoleName")] BusinessRoleViewModel businessRoleViewModel)
        {
            if (id != businessRoleViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                businessRoleService.Update(businessRoleViewModel);
                businessRoleService.Save();

                return RedirectToAction(nameof(Index));
            }
            return View(businessRoleViewModel);
        }

        // GET: BusinessRoles/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var businessRole = businessRoleService.FindById(id);
            if (businessRole == null)
            {
                return NotFound();
            }

            return View(businessRole);
        }

        // POST: BusinessRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            businessRoleService.Delete(id);
            businessRoleService.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SieuNhanGao.Service.IServices;
using SieuNhanGao.Service.ViewModels;
using SieuNhanGao.Utilities.Constaint;
using SieuNhanGaoBlog.Areas.Admin.Data;
using System;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class PostController : Controller
    {
        private IPostService postService;
        private ITagService tagService;
        private ICategoryService categoryService;
        private IPostCategoryService postCategoryService;

        public PostController(IPostService _postService, ITagService _tagService
            , ICategoryService _categoryService
            , IPostCategoryService _postCategoryService
            )
        {
            postService = _postService;
            tagService = _tagService;
            categoryService = _categoryService;
            postCategoryService = _postCategoryService;
        }

        public IActionResult Index()
        {
            var posts = postService.GetAll();
            return View(posts);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            var categories = categoryService.GetAll();
            ViewBag.Categories = new SelectList(categories, "Id", "CategoryName");
            var userId = HttpContext.Session.GetString(UserConstants.USER_ID);
            var post = new PostViewModel
            {
                CreateDate = DateTime.Now,
                UserId = Int32.Parse(userId)
            };
            postService.Add(post);
            postService.Save();
            return View(post);
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Title,Description,Content,Thumbnail,CreateDate,UpdateDate,Status,Alias,UserId,ViewCount")] PostViewModel postVm)
        {
            if (ModelState.IsValid)
            {
                postService.Add(postVm);
                postService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(postVm);
        }

        [Route("Admin/Post/AddCategory")]
        [HttpPost]
        public JsonResult AddCategory([FromBody]PostCategoryViewModel postCateVm)
        {
            bool stt = false;
            string msg = string.Empty;
            var comment = postCategoryService.Add(postCateVm);
            if (comment == null)
            {
                msg = "<div class='alert alert-success'>Add thất bại</div>";
            }
            else
            {
                stt = true;
                msg = "<div class='alert alert-success'>Add thành công</div>";
            }
            postCategoryService.Save();
            return Json(new
            {
                status = stt,
                message = msg
            });
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using SieuNhanGao.Service.IServices;
using SieuNhanGaoBlog.Areas.Admin.Data;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class UserController : Controller
    {
        private IUserService userService;

        public UserController(IUserService _userService)
        {
            userService = _userService;
        }

        public IActionResult Index()
        {
            var users = userService.GetAll();
            return View(users);
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{
    var userName = @Context.Session.GetString("UserName");
    var avatar = @Context.Session.GetString("UserAvatar");
    var isAdmin = @Context.Session.GetString("IsAdmin");
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->
    <link href="~/lib/fontawesome-free/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/lib/ckeditor/skins/moono-lisa/editor.css" rel="stylesheet" />
    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <link href="~/css/style.sea.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <div class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">GaoDo Admin</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
            </ul>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>
            <!-- Nav Item - Pages Collapse Menu -->
            @{
                if (isAdmin.Equals("1"))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                <i class="fas fa-fw fa-cog"></i>
                                <span>Admin</span>
                            </a>
                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                                <div class="bg-white py-2 collapse-inner rounded">
                                    <a class="collapse-item" asp-area="Admin" asp-controller="BusinessRole" asp-action="Index">BusinessRole</a>
                                    <a class="collapse-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                }
            }
            <!-- Nav Item - Utilities Collapse Menu -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
                        <i class="fas fa-fw fa-wrench"></i>
                        <span>Management</span>
                    </a>
                    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" asp-area="Admin" asp-controller="Post" asp-action="Index">Post</a>
                            <a class="collapse-item" asp-area="Admin" asp-controller="Comment" asp-action="Index">Comment</a>
                            <a class="collapse-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                            <a class="collapse-item" asp-area="Admin" asp-controller="Tag" asp-action="Index">Tag</a>
                        </div>
                    </div>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </div>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Begin Page Content -->
                @await Html.PartialAsync("_LoginPartial")
                @RenderBody()
                <!-- End of Main Content -->
            </div>
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <form asp-area="Admin" asp-controller="Home" asp-action="Logout" method="post">
                        <button type="submit" class="btn btn-primary">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>