SieuNhanGaoBlog/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using SieuNhanGao.Service.IServices;
using SieuNhanGaoBlog.Areas.Admin.Data;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class UserController : Controller
    {
        private IUserService userService;

        public UserController(IUserService _userService)
        {
            userService = _userService;
        }

        public IActionResult Index()
        {
            var users = userService.GetAll();
            return View(users);
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SieuNhanGao.Service.IServices;
using SieuNhanGao.Service.ViewModels;
using SieuNhanGaoBlog.Areas.Admin.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SieuNhanGaoBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [ServiceFilter(typeof(AuthorizeBusiness))]
    public class UserRoleController : Controller
    {
        private IBusinessRoleService businessRoleService;
        private IUserRoleService userRoleService;
        private IUserService userService;
        private IRoleService roleService;

        public UserRoleController(IBusinessRoleService _businessRoleService
            , IUserRoleService _userRoleService
            , IUserService _userService
            , IRoleService _roleService)
        {
            businessRoleService = _businessRoleService;
            userRoleService = _userRoleService;
            userService = _userService;
            roleService = _roleService;
        }

        public IActionResult Index(int Id)
        {
            // get bussinessRole
            var businessRoles = businessRoleService.GetAll();
            var itemsBusinessRole = new List<SelectListItem>();
            foreach (var item in businessRoles)
            {
                itemsBusinessRole.Add(new SelectListItem() { Text = item.BusinessRoleName, Value = item.Id });
            }
            ViewBag.itemsBusinessRole = itemsBusinessRole;

            // get userId,UserName của user cần gán quyền
            var user = userService.FindById(Id);
            ViewBag.user = user;

            return View();
        }

        // get UserRole with businessID in Role and userId in UserRole
        public JsonResult getPermissions(string id, int usertemp)
        {
            // getall userrole from userd,bussinessRoleId
            var listuserRoles = userRoleService.userRoles(usertemp, id);
            // getall roles with BusinessRoleId
            var rolesWithBusinessId = roleService.GetRolesWithBusinessRoleId(id);
            //lay cac id permistion da dc gan cho nguoi dung
            var listpermissionID = listuserRoles.Select(p => p.RoleId);
            //so sanh va add them
            foreach (var item in rolesWithBusinessId)
            {
                if (!listpermissionID.Contains(item.RoleId))
                    listuserRoles.Add(item);
            }
            return Json(listuserRoles.OrderBy(x => x.Description));
        }

        public string updatePermission(int id, int usertemp)
        {
            string msg = "";
            var grant = userRoleService.FindById(usertemp, id);
            if (grant == null)
            {
                var userRole = new UserRoleViewModel() { UserId = usertemp, RoleId = id };
                userRoleService.Add(userRole);
                msg = "<div class='alert alert-success'>Cấp quyền thành công</div>";
            }
            else
            {
                userRoleService.Delete(grant);
                msg = "<div class='alert alert-success'>Hủy quyền thành công</div>";
            }
            userRoleService.Save();
            return msg;
        }
    }
}

SieuNhanGaoBlog/Areas/Admin/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<SieuNhanGao.Service.ViewModels.UserViewModel>
@{
    if (Model.Count() <= 0 || Model == null)
    {
        <div class="card shadow mb-4">
            <div class="container-fluid">
                <div class="card-header py-3">
                    <div class="card-header py-3">
                        <p class="m-0 font-weight-bold text-primary">
                            <h3>Notthings!!</h3>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="card shadow mb-4">
            <div class="container-fluid">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Id)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.UserName)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserName)
                                        </td>
                                        <td>
                                            <a asp-area="Admin" asp-controller="User" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                            <a asp-area="Admin" asp-controller="UserRole" asp-action="Index" asp-route-id="@item.Id">Grant Permission</a> |
                                            <a asp-area="Admin" asp-controller="User" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                @* add phan trang *@
            </div>
        </div>
    }
}